## NumPy Basics

'jay'

2 What is NumPy and why is it used in Python?

In [2]:
# they are 3 ways to install the numpy in the system
# 1 ways
!pip install numpy
# 2 ways is take the new file in the folder name it has the requirements.txt (as any thing) and write numpy in the in the installing the requirements.txt in the terminal
# 3 in the termial write the pip install numpy 


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


3 Write a code to create a 1D NumPy array from a list.


In [4]:
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

4 How to find the data type of elements in a NumPy array?

In [5]:
print(type(arr[0]))

<class 'numpy.int64'>


5 Write a code to create a 2D array using NumPy.

In [8]:
arr1 = np.array([[1,2,3,4,5]])
print(arr1)
print(arr1.ndim)

[[1 2 3 4 5]]
2


### Reshape

6 Write code to reshape a 1D array of 12 elements into a 3x4 array.

In [28]:
arr3 = np.arange(12)
print(arr3) # 1D array
print(' ')




[ 0  1  2  3  4  5  6  7  8  9 10 11]
 


In [31]:
arr3.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

7 What will happen if you try to reshape an array with incompatible dimensions?

8 Convert a 2x6 array into a 3x4 array using reshape.

In [23]:
arr3 = np.arange(12)
arr3.reshape(2,6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:
arr3.reshape(3,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

9 How to reshape a 3x3 array into a 1D array?

In [20]:
arr4= np.array([[[1,2,3,4,5]]])
arr4.flatten()




array([1, 2, 3, 4, 5])

10 What is the use of -1 in reshape function?

Ans:-
 it will turn it into orginal shape

### Resize


11 Differentiate between reshape and resize in NumPy.

12 Write code to resize a 2x3 array to 3x2.

In [39]:
a=np.arange(6)
a.resize(2,3)
a


array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
a=np.arange(6)
a.resize(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])