In [1]:
'jay'

'jay'

### What is numpy ?

numpy is library that help us do high level mathematical computation and also the basic of all other eda library.

In [3]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5,])
print(a)

[1 2 3 4 5]


In [6]:
a=[12,13,[15,14]]
a[2][0]

15

In [8]:
list(range(10000))*3

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [11]:
a=np.arange(10000)
a*3

array([    0,     3,     6, ..., 29991, 29994, 29997])

numpy works with array,arrays are comsecutive blocks of memory kept one beside the other

1:- it is homogenoues in nature
2:- It build on C ,thereby making it much faster that python list

In [ ]:
a=np.array([1,2,3,'jay',4+3j])
a 

array(['1', '2', '3', 'jay', '(4+3j)'], dtype='<U64')

 all the values are convert to string because of the hierarcy

str>complex>float>integer>boolean

In [18]:
a=np.array([1,2,3,'jay',4+3j],dtype='object')
print(a) # using the dtype(data Type ) ='object' is their is no change in the datat types of value.
print(type(a))

[1 2 3 'jay' (4+3j)]
<class 'numpy.ndarray'>


numpy is faster because it has contious memory allocation, has same datatype for all teh elements in the array,
fixed itemsize 

In [21]:
### multidemsion array

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
a= np.arange(12) #start with 0 and end with n-1
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
a=np.arange(1,12,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
# resize it is used to convert the 1d to 2d, it is permanent change
a= np.arange(1,12)
a.resize(2,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11,  0]])

In [36]:
a= np.arange(1,12)
a.resize(3,6)
a # it will take the more elemet(0) as printthe o/p

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [33]:
# reshape it used to convert 1D to 2D, it is temperary change
a= np.arange(1,13)
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [1]:
a=np.arange(1,13)
a.reshape(3,6) # it will work on the num of elements present in the array base on that they will arange if we give more it throws the error

NameError: name 'np' is not defined

In [ ]:
a= np.arange(12)
a
print(a.dtype) # datarype
print(a.ndim) # dimension
print(a.itemsize) #bites
print(a.shape) 
print(a.size) # size

int64
1
8
(12,)
12


In [ ]:
a=np.arange(12)
a.resize(3,4)
print(a)
print(a.dtype) # datarype
print(a.ndim) # dimension
print(a.itemsize) #bytes

print(a.shape) # 2 rows and 3 columns
print(a.size) # size

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
int64
2
8
(3, 4)
12


In [52]:
a=np.array([[[ 0 , 1,  2,  3],
            [ 4  ,5,  6 , 7],
             [ 8 , 9 ,10 ,11]]])
a.ndim


3

In [66]:
def array1():
    a= np.array([[1,2,3],[4,5,6]])
    print(f'The data Type of the array is {a.dtype},the Dimenion is {a.ndim} ')
array1()

The data Type of the array is int64,the Dimenion is 2 


In [1]:
# homog,bytes,

In [6]:
import numpy as np
a= np.arange(12)
a.resize(3,4,2)#1st elemnt is dim,2nd number is rows and 3rd number is col
a


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]]])

In [ ]:

a= np.arange(12)
a.reshape(12)
a.reshape(2,6,1) #1st elemnt is dim,2nd number is rows and3rd number is col


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
a= np.arange(12).reshape(2,6,1)

In [10]:
a

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]])

In [12]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [14]:
# ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
a= np.zeros(5)
a.resize(2,3,2)
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.eye(5,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

iniform distribution :- when the data collected from an experiment,where the influence of thw outside factors are negliable on the actual expermint,such points create a uniformdistribution

In [ ]:
a=np.random.rand(2,3,2)
a


np.float64(0.5336808381512319)

In [24]:
a.mean()

np.float64(0.5336808381512319)

array([2, 2], dtype=int32)

In [26]:
# normal distribution:- bell curver,gaussian distribution
np.random.rand(2,4,4)

array([[[0.42018987, 0.54530851, 0.15535545, 0.90771347],
        [0.63858331, 0.37062244, 0.31712966, 0.11806275],
        [0.83726257, 0.59160731, 0.01444285, 0.53182724],
        [0.27071575, 0.96510685, 0.19323986, 0.65820857]],

       [[0.45526937, 0.85425509, 0.0928549 , 0.70578056],
        [0.51984659, 0.54090918, 0.27481217, 0.37733388],
        [0.49521617, 0.53192914, 0.24917361, 0.22618424],
        [0.24607076, 0.54918755, 0.03826593, 0.73928999]]])

In [31]:
def array():
    a=np.zeros(12)
    
    a.resize(2,3,2)
    a
    print(a)

array()
    

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [35]:
def array():
    a=np.eye(12)
    
    a.resize(2,3,2)
    a
    print(a,a.ndim)

array()
    

[[[1. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]] 3


In [38]:
np.random .randint(5)

0

In [39]:
np.random.randint(1,7)

4

In [40]:
np.random.randint(1,7,size =(2,5))

array([[6, 1, 5, 4, 2],
       [1, 6, 2, 4, 5]], dtype=int32)

In [42]:
a=[1,[2,3],7]
lst=[]
for i in a:
    

    if isinstance(i, list):   # if element is a list, extend it
        lst.extend(i)
    lst.append(i)
print(lst)

[1, 2, 3, [2, 3], 7]


In [ ]:
a=[1,[2,3],7]
lst=[]
for i in a:
    

    if isinstance(i, list):   
        lst.extend(i)
    else:
        lst.append(i)
print(lst)

[1, 2, 3, 7]


In [47]:
a=[[12,13],[1,2],[7,8]]
m=[]
for i in a:
    m+=i
print(m)

[12, 13, 1, 2, 7, 8]


In [48]:
a=[[12,13],[1,2],[7,8]]
m=[]
for i in a:
    m.extend(i)
print(m)

[12, 13, 1, 2, 7, 8]


In [49]:
a=[[12,13],[1,2],[7,8]]
a=np.array(a)
a.flatten()

array([12, 13,  1,  2,  7,  8])

In [50]:
a=[[12,13],[1,2],[7,8]]
a=np.array(a)
a.ravel()

array([12, 13,  1,  2,  7,  8])

In [51]:
## flatten and ravel or temperature changes

In [54]:
np.array([12, 13,  1,  2,  7,  8])
np.random.permutation([12, 13,  1,  2,  7,  8])

array([ 1,  7, 12,  2, 13,  8])

In [57]:
a=np.random.shuffle([12, 13,  1,  2,  7,  8])

In [58]:
a

In [62]:
a=np.array([12,1,2,3])
a.argsort() # sorting in asc giveing the indexing values

array([1, 2, 3, 0])

In [63]:
a=np.array([12,1,2,3])
a.argmax() #index of max value

np.int64(0)

In [64]:
a=np.array([12,1,2,3])
a.argmin() #indexof the min

np.int64(1)

In [2]:
#sort
import numpy as np
#a = np.array([[[2,13,14]],[[11,220,3]],[[500.57,5]]])
a= np.arange(9)
a.resize(2,3,2)
#print('****')
#print(np.sort(a,axis=1)) # row level
#print('****')
#print(np.sort(a,axis=0)) # column level
a[0][0][1]=999 #updation
a[1][0:2]
a[1,:2]=[[1200,5],[700,28]]
print('*****')
a[0][1:]=[[120,6],[500,9]]
#print(a)
#print('****')
print(np.sort(a,axis=2))
a

*****
[[[   0  999]
  [   6  120]
  [   9  500]]

 [[   5 1200]
  [  28  700]
  [   0    0]]]


array([[[   0,  999],
        [ 120,    6],
        [ 500,    9]],

       [[1200,    5],
        [ 700,   28],
        [   0,    0]]])

In [ ]:
# insertion and deletion
a= np.arange(12)
a.resize(2,3,2)
#a[1,2,1]
b =np.delete(a,0) #doing the indexing
c=np.delete(a,[2,3])
d=np.delete(a,[7,8])
e=np.delete(a,[2,2],axis=1)

f= np.delete(a,2,axis =1)
g=np.delete(a,[1,1],axis=0)
print(a)
print('b:',b)
print(' ')
print('c:',c)
print(' ')
print('d:',d)
print(' ')
print('e:',e)
print(' ')
print('f:',f)

print('g:',g)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
b: [ 1  2  3  4  5  6  7  8  9 10 11]
 
c: [ 0  1  4  5  6  7  8  9 10 11]
 
d: [ 0  1  2  3  4  5  6  9 10 11]
 
e: [[[0 1]
  [2 3]]

 [[6 7]
  [8 9]]]
 
f: [[[0 1]
  [2 3]]

 [[6 7]
  [8 9]]]
g: [[[0 1]
  [2 3]
  [4 5]]]


In [14]:
a[1,2,1]=12
print(a)
d= np.delete(a,11)
print('d:',d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 12]]]
d: [ 0  1  2  3  4  5  6  7  8  9 10]


In [29]:

f= np.delete(a,1,axis =0)
f

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [31]:
a= np.arange(12)
a.resize(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [33]:
d=np.delete(a,[0,1])

d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
d.resize(2,3,2)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [37]:
e=np.delete(a,[2,1],axis=1)
print('e:',e)
b=np.delete(a,0,axis=1)
print('b:',b)


e: [[[0 1]]

 [[6 7]]]
b: [[[ 2  3]
  [ 4  5]]

 [[ 8  9]
  [10 11]]]


In [39]:
import numpy as np
a= np.arange(12)
a.resize(2,3)
a[0][0]=899
print(a)
n=np.delete(a,[1],axis=1)
print('******')
print(n)

[[899   1   2]
 [  3   4   5]]
******
[[899   2]
 [  3   5]]


In [40]:
b = np.delete(a[0],0,axis=0)
A=np.array([b,a[1]],dtype=object)
print(A)

[array([1, 2]) array([3, 4, 5])]


In [43]:
a= np.array([[12,13,14],[23,44,55]])
b= np.array([[7,8,9],[3,4,5]])
c=np.hstack((a,b))
print(c)
print('****')
d=np.vstack((a,b))
print(d)
print('****')
e=np.dstack((a,b))
print(e)
print('****')

[[12 13 14  7  8  9]
 [23 44 55  3  4  5]]
****
[[12 13 14]
 [23 44 55]
 [ 7  8  9]
 [ 3  4  5]]
****
[[[12  7]
  [13  8]
  [14  9]]

 [[23  3]
  [44  4]
  [55  5]]]
****
